http:
  host : http://120.78.168.146:8083
  timeout : 1.0
header :
  Content-Type : 'application/json;charset=UTF-8'

common_token:
  path : /get/token
  user_name : user1
  password : 123456

logger :
  console_level : "DEBUG"
  file_level : "INFO"
  format : "%(asctime)s - [line:%(lineno)d]-%(name)s -%(levelname)s - %(message)s"
  datefmt : '%Y/%m/%d %H:%M:%S'

database_info :
  database : learn
  host : 120.78.168.146
  username : root
  password : 1111
  port : 3306

email_info:
  stmp_host : smtp.qq.com
  mail_user : 1401482005@qq.com
  stmp_password: xxxxx
  stmp_port : 465
  sender : 1401482005@qq.com
  receiver : 1401482005@qq.com/1401482005@qq.com
  title : 接口测试报告
  content : 接口测试报告发送
  testuser : someone
  on_off : "1"



