http:
  host : https://driver-taxi.vvip-u.com
  timeout : 1.0


logger :
  console_level : "DEBUG"
  file_level : "INFO"
  format : "%(asctime)s - [line:%(lineno)d]-%(name)s -%(levelname)s - %(message)s"
  datefmt : '%Y/%m/%d %H:%M:%S'

database_info :
  database : test
  host : 120.78.168.146
  username : root
  password : 123456
  port : 3306


